---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - podreaper.com.podreaper.com
  resources:
  - podreaperconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podreaper.com.podreaper.com
  resources:
  - podreaperconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - podreaper.com.podreaper.com
  resources:
  - podreaperconfigs/status
  verbs:
  - get
  - patch
  - update
